baseURL = "http://example.org/"
languageCode = "en-us"
title = "Bhavya Goel"
theme = [
    # "gruvhugo", 
    # "hugo-coder", 
    "hugo-refresh", 
    # "hugo-theme-introduction", 
    "toha", 
    
]
