#!/bin/sh

# If a command fails then the deploy stops
set -e

printf "\033[0;32mDeploying updates to GitHub bhavyagoel.dev.repo...\033[0m\n"

# Deleting the existing build
printf "\033[0;32mDeleting existing build {/public}\033[0m\n"
rm -rf public
printf "%s\n" "Last built deleted!!"

# Building the main home page
msg_main="Rebuilding site (hugo -D) $(date)"
if [ -n "$*" ]; then
	msg="$*"
fi
printf '%s\n' "$msg_main"
hugo -D
printf '%s\n' "Updated home page built!!"

# Building Codes Section 
msg_main="Rebuilding site (hugo -D --config=config_codes.yaml) $(date)"
if [ -n "$*" ]; then
	msg="$*"
fi
printf "\033[0;32m $(msg_main) \033[0m\n"
hugo -D --config=config_codes.yaml
printf '\033[0;32mUpdated code page built!!\033[0m\n'

# Deleting content from main repo 
printf "\033[0;32mDeleting the content in bhavyagoel.github.io\033[0m\n"
rm -rf /home/heisenberg/GitHubProj/bhavyagoel.github.io/*
printf "%s\n" "Deleted!!"

# Copying new build to main repo
printf "\033[0;32mCopying the content to bhavyagoel.github.io\033[0m\n"
cp -a public/. /home/heisenberg/GitHubProj/bhavyagoel.github.io/
printf "%s\n" "Copied!!"

# Input commit message
printf '\033[0;32mEnter the commit message (bhavyagoel.dev.repo): \033[0m'
read -r msg_1
git add .
git commit -m "$msg_1 [Autogenerated] $(date)"
git push -u origin main 
printf '\033[0;32mSuccessfully Git Pushed bhavyagoel.dev.repo\033[0m\n'

# Changing directories and push 
cd /home/heisenberg/GitHubProj/bhavyagoel.github.io/
echo $(pwd)
printf '\033[0;32mEnter the commit message (bhavyagoel.github.io): \033[0m'
read -r msg_2
git add .
git commit -m "$msg_2 [Autogenerated] $(date)"
git push -u origin main 
printf '\033[0;32mSuccessfully Git Pushed bhavyagoel.github.io\033[0m\n'





